### ISSUE TITLE
Live demo?

### ISSUE THREAD

**Issue by dandv** [hackerwins/winternote#1]
Can we see Winternote in action somewhere?

**Comment by hackerwins** [comment]
@dandv Thanks for the first question.
Now We don't have demo page, because Winternote is under development. Basic text editing version will takes 3months or more.

So I attach gif for current development version. We can do insert text and backspace only
.
![jun 03 2015 10 07](https://cloud.githubusercontent.com/assets/2059311/7950603/50e080b2-09d8-11e5-8683-ecfc9fa5fee8.gif)

**Comment by daewon** [comment]
it's amazing!

**Comment by hackerwins** [comment]
@daewon I hope you join this project soon.

**Comment by lygstate** [comment]
@HackerWins summernote have so mush issues, well ,do this project have testing framework things?

That's seems a must be..

**Comment by hackerwins** [comment]
@lygstate Yeap. I agree.
